module.exports = {
    userController: require('./controllers/userController'),
    userLotusController: require('./controllers/userLotusController'),
    userCasinoController: require('./controllers/userCasinoController'),
    marketsController: require('./controllers/marketsController'),
    matchesController: require('./controllers/matchesController'),
    seriesController: require('./controllers/seriesController'),
    sportsController: require('./controllers/sportsController'),
    fancyController: require('./controllers/fancyController'),
    accountStatementsController: require('./controllers/accountStatementsController'),
    globalSettingController: require('./controllers/globalSettingController'),
    betsController: require('./controllers/betsController'),
    matkabetsController: require('./controllers/matkabetsController'),
    adminMatchController: require('./controllers/adminMatchController'),
    dashboardController: require('./controllers/dashboardController'),
    userSettingController: require('./controllers/userSettingController'),
    exchangeController: require('./controllers/exchangeController'),
    reportController: require('./controllers/reportController'),
    livelineController: require('./controllers/livelineController'),
    uploadController: require('./controllers/uploadController'),
    userSuperNovaController: require('./controllers/userSuperNovaController'),
};
